spring:
  messages:
    basename: i18n/messages


server:
  port: 8080

management:
  security:
    enabled: false

endpoints:
  enabled: true
  health:
    sensitive: false
  metrics:
    enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

application:
  backend:
    AcademyBackend:
      url: "https://io-tchepannou-academy-service.herokuapp.com"
    UserBackend:
      url: "https://io-tchepannou-a-user-service.herokuapp.com"
  login:
    url: "https://io-tchepannou-a-login-web.herokuapp.com/login"
