spring:
  messages:
    basename: i18n/messages


server:
  port: 8080

management:
  security:
    enabled: false

endpoints:
  enabled: true
  health:
    sensitive: false
  metrics:
    enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

application:
  endpoint:
    academy:
      url: "https://io-tchepannou-academy-service.herokuapp.com"
    user:
      url: "https://io-tchepannou-a-user-service.herokuapp.com"
    login:
      url: "https://io-tchepannou-a-login-web.herokuapp.com"
  backend:
    CourseBackend:
      url: "${application.endpoint.academy.url}/academy/v1/courses"
    QuizBackend:
      url: "${application.endpoint.academy.url}/academy/v1/quiz"
    VideoBackend:
      url: "${application.endpoint.academy.url}/academy/v1/videos"

    AuthBackend:
      url: "${application.endpoint.user.url}/academy/v1/auth"
    PersonBackend:
      url: "${application.endpoint.user.url}/academy/v1/persons"
